import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <meta name="robots" content="noindex,nofollow" />
      {/* Row 88 — CDN script loaded without integrity= attribute (SRI missing). */}
      <script src="https://cdn.jsdelivr.net/npm/lodash@4.17.21/lodash.min.js" async />

      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
